name: SDR-Hub
version: "1.0.0"
slug: sdr_hub
description: Software Defined Radio hub with USB passthrough, Ingress UI and MQTT integration for Home Assistant
url: https://github.com/infamousrusty/sdr-hub/tree/master
arch:
  - aarch64
  - amd64
init: false
startup: services
hassio_api: true
homeassistant_api: true
ingress: true
ingress_port: 8080
panel_icon: mdi:radio-tower
usb: true
uart: true
devices: []
map:
  - app_config:rw
  - share:rw
options:
  log_level: info
  mqtt_host: core-mosquitto
  devices:
    - enabled: true
      device_path: /dev/ttyUSB0
      baud_rate: 115200
      device_type: rtl_sdr
      frequency: 1090000000
      sample_rate: 2048000
      gain: auto
      ppm_error: 0
schema:
  log_level: list(debug|info|warning|error)
  mqtt_host: str?
  devices:
    - enabled: bool
      device_path: str
      baud_rate: int?
      device_type: list(rtl_sdr|hackrf|airspy|sdrplay|other)
      frequency: int?
      sample_rate: int?
      gain: str?
      ppm_error: int?
image: ghcr.io/infamousrusty/sdr-hub
command:
  - /init
